---
- hosts: webserver
  become: yes
  tasks:
  - name: display host of sysytem
    command: hostname -f
    register: myresult

  - name: display the result
    debug:
     msg: "{myresult}"

  - name: install git on machine
    apt:
     name: git
     state: present
    when: myresult.stderr ==""

  - name: install tree on machine
    apt:
     name: tree
     state: present
    when: myresult.stderr !=""
    