---
- hosts: all
  become: yes
  tasks:
  - name: install git on all nodes
    apt:
      name: git
      state: present

  - name: restart git on all nodes
    service:
      name: git
      state: restart    